myblog/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import staticfiles
from django.conf.urls import url,patterns,include
from django.contrib import admin
from myblog.blogs import views

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myblog.views.home', name='home'),
    # url(r'^myblog/', include('myblog.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^$', views.blog_list),
    url(r'^index/?$', views.blog_list),
    url(r'^admin/', include(views.blog_list)),
    url(r'^blog/list$', views.blog_list),
    url(r'^blog/form$', views.blog_form),
    url(r'^blog/delete$', views.blog_del),
    url(r'^blog/view$', views.blog_view),
    url(r'^blog/edit$', views.blog_edit),
    url(r'^aboutme$', views.aboutme),
    #url(r'^site_media/(?P<path>.*)','django.views.static.serve',{'document_root':'home/desktop/myblog/myblog/blogs/static'}),
    # url(r'/(?P<path>.*)','django.views.static.serve',{'document_root':'/blogs/static'}),
)
# urlpatterns += staticfiles_urlpatterns()
# #urlpatterns += staticfiles_urlpatterns()

myblog/blogs/models.py
#coding=utf-8
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(u'标题', max_length=50)
    author = models.CharField(u'作者', max_length=10)
    content = models.CharField(u'正文', max_length=2000)
    post_date = models.DateTimeField(u'发布时间',auto_now_add=True)
    class Meta:
        ordering = ['-post_date']

myblog/forms.py
#coding=utf-8

from django import forms

class BlogForm(forms.Form):
    title =  forms.CharField(label='标题')
    author = forms.CharField(label='作者')
    content = forms.CharField(label='正文',widget=forms.Textarea)

myblog/blogs/views.py
# coding=utf-8

from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from myblog.blogs.models import Blog
from myblog import forms
from django.template import RequestContext


def test(request):
    return render_to_response('test.html', {'test': test})


def aboutme(request):
    return render_to_response('aboutme.html', {'aboutme': aboutme})


def blog_list(request):
    blog_list = Blog.objects.all()
    return render_to_response('blog_list.html', {'blog_list': blog_list})


def blog_form(request):
    if request.method == 'POST':
        form = forms.BlogForm(request.POST)
        if form.is_valid():
            data = form.data
            if not data['id']:
                blog = Blog(title=data['title'], author=data['author'], content=data['content'])
                blog.save()
            else:
                blog = Blog.objects.get(id=data['id'])
                blog.title = data['title']
                blog.author = data['author']
                blog.content = data['content']
                blog.save()
            return HttpResponseRedirect('/blog/list')
        else:
            return render_to_response('blog_form.html', {'form': form}, context_instance=RequestContext(request))
    else:
        form = forms.BlogForm()
        return render_to_response('blog_form.html', {'form': form}, context_instance=RequestContext(request))


def blog_del(request):
    errors = []
    if 'id' in request.GET:
        bid_ = request.GET['id']
        Blog.objects.filter(id=bid_).delete()
        return HttpResponseRedirect('/blog/list')
    else:
        errors.append("参数异常请刷新后重试")
        return render_to_response('blog_list.html', {'errors': errors})


def blog_view(request):
    errors = []
    if 'id' in request.GET:
        bid_ = request.GET['id']
        blog = Blog.objects.get(id=bid_)
        return render_to_response('blog_view.html', {'blog': blog})
    else:
        errors.append("参数异常请刷新后重试")
        # return render_to_response("blog_list.hmtl",{'errors':errors})


def blog_edit(request):
    errors = []
    if 'id' in request.GET:
        bid_ = request.GET['id']
        blog = Blog.objects.get(id=bid_)
        form = forms.BlogForm(
            initial={'id': blog.id, 'title': blog.title, 'author': blog.author, 'content': blog.content}
        )
        return render_to_response('blog_form.html', {'form': form, 'blog': blog},
                                  context_instance=RequestContext(request))
    else:
        errors.append("参数异常请刷新后重试")
        return render_to_response("blog_list.html", {'errors': errors})

myblog/blogs/templates/about_me.html
{% load static from staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'blogs/style.css' %}">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<html>
<head>
	<title>About Me</title>
</head>
<body>
   {% if errors %}
    <ul>
        {% for error in errors %}
        <li style="color: red;">{{error}}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <dir>
    	<h1 align="center">About Me</h1>
        <p><img src="{% static "/blogs/images/aboutme.jpg" %}"></p>
    </dir>
</body>
</html>

myblog/blogs/templates/aboutme.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'blogs/style.css' %}">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<style type="text/css">
          body {
            color:black;;
            background: url("http://7xjhx2.com1.z0.glb.clouddn.com/bg.jpg");
            padding: 0 5em;
            margin: 0;
            width:100%;
            height:100%;
        }
</style>
<html>
<head>
	<title>About Me</title>
</head>

<body>
   {% if errors %}
    <ul>
        {% for error in errors %}
        <li style="color: red;">{{error}}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <dir>
    	<h1 align="center">About Me</h1>
        <p align="center"><a href="/blog/list">Go Back To HomePage</a></p>
    	<p align="center">
            <!--{% static "/static/blogs/images/aboutme.png" as myphoto %}-->
        <!--<img src="{{ myphoto }}" alt="aboutme!" /></p>-->
        <img src="http://7xjhx2.com1.z0.glb.clouddn.com/aboutme.png" alt="aboutme!" /></p>
    </dir>
</body>
</html>

myblog/blogs/templates/base.html
<html>
      <style type="text/css">
          body {
            background: white url("http://7xjhx2.com1.z0.glb.clouddn.com/bg.jpg") no-repeat right bottom;
            color:#efd;
            width:100%;
            height:100%;
            padding: 0 5em;
            margin: 0
        }
        h1{padding:2em 1em;background:#675}
        h2{color:#bf8;border-top:1px dotted #fff;margin-top:2em}
        p{margin:1em 0}
      </style>
     
      <body>
        {% block content %}
        {% endblock %}s
      </body>
</html>

myblog/blogs/templates/blog_form.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'blogs/style.css' %}">

<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>

<html>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title>Edit Blogs</title>
    <head></head>
    <style type="text/css">
        body {
             color:black;;
            background: url("http://7xjhx2.com1.z0.glb.clouddn.com/bg.jpg");
            padding: 0 5em;
            margin: 0;
            width:100%;
            height:100%;
        }

        h2 {
            border-top: 1px dotted #efd;
            margin-top: 2em
        }

        p {
            margin: 1em 0;
            
        }
    </style>    
    <body color='#FF8C00'>
       {% if errors %}
        <ul>
            {% for error in errors %}
            <li style="color: red;">{{error}}</li>
            {% endfor %}
        </ul>
        {% endif %}
    <h1>Edit Blogs</h1>
    <p><a href="/blog/list">Go Back To HomePage </a>
    <!-- <form action="/blog/form" method="post"> -->
    <form action="/blog/form" method="post">{% csrf_token %}
       <!-- <input name="csrfmiddlewaretoken" value="V9e6XHyDiEizZMaq6BdgQDDlE1wH4Lcy" type="hidden"> -->
       <table>
            <tbody>
                <td><input id="id" name="id" type="hidden" value={{ blog.id }}></td></tr>
                <tr><th><label for="id_title">Title </label></th>
                    <td><input id="title" name="title" type="text" value={{ blog.title }}></td></tr>
                <tr><th><label for="id_author">Author</label></th>
                    <td><input id="author" name="author" type="text" value={{ blog.author }}></td></tr>
                <tr><th><label for="id_content">Content </label></th>
                    <td><textarea id="content" name="content" cols="80" rows="10">{{ blog.content }}</textarea></td></tr>
            </tbody>
        </table>

        <P>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input value="save" type="submit"></P>
    </form>       
       
    </body>
</html>

myblog/blogs/templates/blog_list.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'blogs/style.css' %}">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<style type="text/css">
          body {
            color:black;;
            background: url("http://7xjhx2.com1.z0.glb.clouddn.com/bg.jpg");
            padding: 0 5em;
            margin: 0;
            width:100%;
            height:100%;
        }
</style>
<html>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title>Homepage</title>
    <head>
    </head>
    <body>
       {% if errors %}
        <ul>
            {% for error in errors %}
            <li style="color: red;">{{error}}</li>
            {% endfor %}
        </ul>
        {% endif %}
    <div>
        <h1 align="center">LiShuo's Blog</h1>
        <p align="center"><a href="/blog/form">Write more</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/aboutme">About Me</a></p>
    </div>
    {% for blog in blog_list %}
    <div>
        <h2 align="center"><a href="/blog/view?id={{blog.id}}">{{blog.title}}</a></h2>
        <p align="center">&nbsp;&nbsp;&nbsp;Author: {{blog.author}}&nbsp;&nbsp;&nbsp;published: {{blog.post_date | date:"Y-m-d H:i:s"}}</p>
        <p align="center">&nbsp;&nbsp;&nbsp;DO: &nbsp;<a href="/blog/edit?id={{blog.id}}">Update</a>&nbsp;&nbsp;&nbsp;OR&nbsp;&nbsp;&nbsp;<a href="/blog/delete?id={{blog.id}}">Delete</a></p>
        <p align="center">❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀❀</p>
    </div>
    {% empty %}
        <p align="center">There's no blog.</p>
    {% endfor %}

myblog/blogs/templates/blog_view.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'blogs/style.css' %}">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<html>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title>{{blog.title}}</title>
    <head></head>
     <style type="text/css">
        body {
            color:black;;
            background: url("http://7xjhx2.com1.z0.glb.clouddn.com/bg.jpg");
            padding: 0 5em;
            margin: 0;
            width:100%;
            height:100%;
        }
        h2 {
            color: black;
            border-top: 1px dotted #fff;
            margin-top: 2em
        }
        p {
            color: black;
            margin: 1em 0;
            text-indent:2em
        }
    </style>
    <body>
       {% if errors %}
        <ul>
            {% for error in errors %}
            <li style="color: red;">{{error}}</li>
            {% endfor %}
        </ul>
        {% endif %}

    <h1>{{blog.title}}</h1>
    <p><a href="/blog/list">Go Back To HomePage</a></p>
    <p>Author：{{blog.author}}{{blog.post_date | date:'Y-m-d H:i:s'}}<p>
    <p>{{blog.content|linebreaks|safe}}</p>
    </body>
</html>